"""Neural watermark remover.

A compact residual U-Net trained specifically on the Device Parts
watermark.  Training pairs are generated by compositing the *learned*
watermark (the alpha matte and color fitted by ``estimate``) onto real
product-photo textures with scale / opacity / JPEG augmentation, so the
network learns to invert the exact blend — including compression
artifacts and the partial-alpha stroke edges where the analytic unblend
leaves faint residues.

Input:  4 channels — watermarked RGB (0-1) + the model's alpha matte.
Output: 3-channel residual; clean = input − residual.

Inference tiles the watermark region at full resolution and only ever
modifies pixels inside the (feathered) footprint, so the rest of the
photo stays bit-identical.
"""

from __future__ import annotations

import numpy as np

try:
    import torch
    import torch.nn as nn
    TORCH_OK = True
except Exception:  # pragma: no cover - torch is optional
    TORCH_OK = False
    nn = None


if TORCH_OK:

    class _Block(nn.Module):
        def __init__(self, cin, cout):
            super().__init__()
            self.net = nn.Sequential(
                nn.Conv2d(cin, cout, 3, padding=1), nn.ReLU(inplace=True),
                nn.Conv2d(cout, cout, 3, padding=1), nn.ReLU(inplace=True),
            )

        def forward(self, x):
            return self.net(x)

    class WMNet(nn.Module):
        """Small 3-scale residual U-Net (~450k params)."""

        def __init__(self, base=24):
            super().__init__()
            self.enc1 = _Block(4, base)
            self.enc2 = _Block(base, base * 2)
            self.enc3 = _Block(base * 2, base * 4)
            self.pool = nn.MaxPool2d(2)
            self.up2 = nn.ConvTranspose2d(base * 4, base * 2, 2, stride=2)
            self.dec2 = _Block(base * 4, base * 2)
            self.up1 = nn.ConvTranspose2d(base * 2, base, 2, stride=2)
            self.dec1 = _Block(base * 2, base)
            self.out = nn.Conv2d(base, 3, 1)

        def forward(self, x):
            e1 = self.enc1(x)
            e2 = self.enc2(self.pool(e1))
            e3 = self.enc3(self.pool(e2))
            d2 = self.dec2(torch.cat([self.up2(e3), e2], 1))
            d1 = self.dec1(torch.cat([self.up1(d2), e1], 1))
            return self.out(d1)


def load_net(weights_path: str, device: str = "cpu"):
    if not TORCH_OK:
        raise RuntimeError("PyTorch is not installed; pip install torch")
    net = WMNet()
    state = torch.load(weights_path, map_location=device, weights_only=True)
    net.load_state_dict(state)
    net.eval()
    return net


def remove_neural(image_rgb: np.ndarray, model, net,
                  tile: int = 256, overlap: int = 32) -> np.ndarray:
    """Run the network over the watermark region of ``image_rgb`` using the
    WatermarkModel for the matte + footprint.  Returns a new image."""
    if not TORCH_OK:
        raise RuntimeError("PyTorch is not installed; pip install torch")
    from .remove import remove_unblend  # analytic first pass

    if image_rgb.shape[:2] != model.image_shape:
        model = model.rescaled(image_rgb.shape[:2])
    unblended = remove_unblend(image_rgb, model, denoise=False)
    x, y, w, h = model.bbox
    H, W = image_rgb.shape[:2]
    # pad the working box so tiles have context beyond the footprint
    pad = 24
    x0, y0 = max(0, x - pad), max(0, y - pad)
    x1, y1 = min(W, x + w + pad), min(H, y + h + pad)
    crop = unblended[y0:y1, x0:x1].astype(np.float32) / 255.0
    matte = np.zeros((H, W), np.float32)
    matte[y:y + h, x:x + w] = model.alpha
    matte_c = matte[y0:y1, x0:x1]

    out = crop.copy()
    ch, cw = crop.shape[:2]
    step = tile - 2 * overlap
    with torch.no_grad():
        for ty in range(0, max(ch - 2 * overlap, 1), step):
            for tx in range(0, max(cw - 2 * overlap, 1), step):
                ey, ex = min(ty + tile, ch), min(tx + tile, cw)
                sy, sx = max(0, ey - tile), max(0, ex - tile)
                patch = crop[sy:ey, sx:ex]
                mp = matte_c[sy:ey, sx:ex]
                ph, pw = patch.shape[:2]
                py, px = (16 - ph % 16) % 16, (16 - pw % 16) % 16
                if py or px:
                    patch = np.pad(patch, ((0, py), (0, px), (0, 0)), mode="reflect")
                    mp = np.pad(mp, ((0, py), (0, px)), mode="reflect")
                inp = np.concatenate([patch, mp[..., None]], axis=2)
                t = torch.from_numpy(inp.transpose(2, 0, 1))[None]
                resid = net(t)[0].numpy().transpose(1, 2, 0)[:ph, :pw]
                # physical bound: a leftover of the watermark cannot exceed
                # ~alpha*220 + 14; clip the correction so the net can never
                # hallucinate beyond what the blend model allows
                cap = (mp[:ph, :pw, None] * 220.0 + 14.0) / 255.0
                resid = np.clip(resid, -cap, cap)
                # never darken a pixel below ~5/255: a positive residual
                # (darkening) larger than the pixel's own brightness would
                # stamp pure black, which no watermark leftover explains
                resid = np.minimum(resid, np.maximum(patch[:ph, :pw] - 0.02, 0.0))
                pred = patch[:ph, :pw] - resid
                # stitch with feathered borders
                wy = np.ones(ph, np.float32)
                wx = np.ones(pw, np.float32)
                if sy > 0:
                    wy[:overlap] = np.linspace(0, 1, overlap)
                if ey < ch:
                    wy[-overlap:] = np.linspace(1, 0, overlap)
                if sx > 0:
                    wx[:overlap] = np.linspace(0, 1, overlap)
                if ex < cw:
                    wx[-overlap:] = np.linspace(1, 0, overlap)
                wmap = (wy[:, None] * wx[None, :])[..., None]
                out[sy:ey, sx:ex] = out[sy:ey, sx:ex] * (1 - wmap) + pred * wmap

    # composite: only footprint pixels change
    import cv2
    foot = cv2.dilate((matte_c > 0.015).astype(np.float32), np.ones((7, 7), np.uint8))
    foot = cv2.GaussianBlur(foot, (0, 0), 2.0)[..., None]
    final = crop * (1 - foot) + out * foot
    result = image_rgb.astype(np.float32).copy()
    result[y0:y1, x0:x1] = np.clip(final * 255.0, 0, 255)
    return result
